version: "2.2"
services:
  #----------------------------------------------------------------------------
  # Chat Bot
  #----------------------------------------------------------------------------
  bot:
    image: openjdk:8-alpine
    command: java -cp /analyzer.jar de.prkz.twitch.emoteanalyser.bot.Bot kafka:9092 moonmoon_ow
    container_name: tca_bot
    volumes:
      - ./target/emote-analyzer-1.0-SNAPSHOT.jar:/analyzer.jar:ro
    links:
      - kafka
    restart: always

  #----------------------------------------------------------------------------
  # Zookeeper
  #----------------------------------------------------------------------------
  zookeeper:
    image: zookeeper
    container_name: tca_zookeeper
    expose:
      - "2181"
    restart: always
  
  #----------------------------------------------------------------------------
  # Kafka
  #----------------------------------------------------------------------------
  kafka:
    build: ./kafka
    entrypoint: wait-for.sh --wait-for zookeeper:2181 --delay 5s
    command: start-kafka.sh
    container_name: tca_kafka
    volumes:
      - ./kafka-storage:/kafka
    expose:
      - "9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: "kafka"
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_DELETE_TOPIC_ENABLE: "true"
      KAFKA_NUM_PARTITIONS: 1
      KAFKA_OFFSETS_RETENTION_MINUTES: 43200
      KAFKA_LOG_RETENTION_HOURS: 720
    links:
      - zookeeper
    restart: always
  
  #----------------------------------------------------------------------------
  # Flink
  #----------------------------------------------------------------------------
  flink-jobmanager:
    image: flink:1.6.3
    command: jobmanager
    container_name: flink-jobmanager
    expose:
      - "6123"
    ports:
      - "8081:8081"
    environment:
      JOB_MANAGER_RPC_ADDRESS: flink-jobmanager
    volumes:
      - ./flink-jobmanager-data:/data
    links:
      - db
    restart: always
  
  flink-taskmanager:
    image: flink:1.6.3
    command: taskmanager
    container_name: flink-taskmanager    
    ports:
      - "6121"
      - "6122"
    environment:
      JOB_MANAGER_RPC_ADDRESS: flink-jobmanager
    volumes:
      - ./flink-conf/log4j-console.properties:/opt/flink/conf/log4j-console.properties
      - ./flink-conf/logback-console.xml:/opt/flink/conf/logback-console.properties
      - ./flink-taskmanager-data:/data
    links:
      - flink-jobmanager
      - db
      - zookeeper
      - kafka
    restart: always

  #----------------------------------------------------------------------------
  # Postgres
  #----------------------------------------------------------------------------
  db:
    image: postgres:alpine
    command: postgres -c 'config_file=/etc/postgresql/postgresql.conf'
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: twitch
    volumes:
      - ./db-storage:/var/lib/postgresql/data
      - ./postgresql/postgresql.conf:/etc/postgresql/postgresql.conf
    expose:
      - "5432"
    restart: always

  #----------------------------------------------------------------------------
  # Dashboard / Frontend
  #----------------------------------------------------------------------------
  dashboard:
    image: dashboard
    build: ./dashboard
    ports:
      - "8082:80"
    volumes:
      - ./dashboard:/var/www/html
      - ./dashboard/php.ini:/usr/local/etc/php/php-dashboard.ini:ro
    links:
      - db
    restart: always
