version: "2.2"

services:
  flink-jobmanager:
    image: flink
    command: jobmanager
    container_name: flink-jobmanager
    expose:
      - "6123"
    ports:
      - "8081:8081"
    environment:
      JOB_MANAGER_RPC_ADDRESS: flink-jobmanager
    links:
      - db
    restart: always
  
  flink-taskmanager:
    image: flink
    command: taskmanager
    container_name: flink-taskmanager    
    ports:
      - "6121"
      - "6122"
    environment:
      JOB_MANAGER_RPC_ADDRESS: flink-jobmanager
    volumes:
      - ./flink-conf/log4j-console.properties:/opt/flink/conf/log4j-console.properties
      - ./flink-conf/logback-console.xml:/opt/flink/conf/logback-console.properties
    links:
      - flink-jobmanager
      - db
    restart: always

  db:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: twitch
    volumes:
      - ./db-storage:/var/lib/postgresql/data
    expose:
      - "5432"
    restart: always

  dashboard:
    image: dashboard
    build: ./dashboard
    ports:
      - "8082:80"
    volumes:
      - ./dashboard:/var/www/html
      - ./dashboard/php.ini:/usr/local/etc/php/php-dashboard.ini:ro
    links:
      - db
    restart: always
