version: "2.2"

services:
  flink-jobmanager:
    image: flink
    command: jobmanager
    container_name: flink-jobmanager
    expose:
      - "6123"
    ports:
      - "8081:8081"
    environment:
      JOB_MANAGER_RPC_ADDRESS: flink-jobmanager
    links:
      - db
  
  flink-taskmanager:
    image: flink
    command: taskmanager
    container_name: flink-taskmanager    
    ports:
      - "6121"
      - "6122"
    environment:
      JOB_MANAGER_RPC_ADDRESS: flink-jobmanager
    links:
      - flink-jobmanager
      - db

  db:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: twitch
    expose:
      - "5432"

  dashboard:
    image: dashboard
    build: ./dashboard
    ports:
      - "8082:80"
    volumes:
      - ./dashboard:/var/www/html
    links:
      - db
