version: "2.2"

services:
  flink:
    image: flink
    command: local
    container_name: flink
    expose:
      - "6123"
    ports:
      - "8081:8081"
    links:
      - db

  db:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: twitch
    expose:
      - "5432"

  dashboard:
    image: dashboard
    build: ./dashboard
    ports:
      - "8082:80"
    volumes:
      - ./dashboard:/var/www/html
    links:
      - db
